#!/usr/bin/env bash
# Provision a new tenant: one organization + one site + its domains +
# one API token. Prints credentials (to stdout AND to
# deploy/<org_slug>.env) that you hand to the client.
#
# Usage:
#   ORG_SLUG=acme ORG_NAME="Acme Corp" \
#     SITE_NAME="Acme Marketing Site" DOMAINS="acme.com,www.acme.com" \
#     bash deploy/provision-site.sh
#
# Or on the Lightsail box:
#   cd /opt/webalytics && set -a && source .env.prod && set +a \
#     && ORG_SLUG=... bash deploy/provision-site.sh
#
# Re-running is safe and idempotent for the org/site/domains. The
# token is always rotated (delete-then-insert) so the file output
# is the current truth.

set -euo pipefail

: "${ORG_SLUG:?ORG_SLUG required (url-safe id, e.g. 'acme')}"
: "${ORG_NAME:?ORG_NAME required (display name, e.g. 'Acme Corp')}"
: "${SITE_NAME:?SITE_NAME required (e.g. 'Acme Marketing')}"
: "${DOMAINS:?DOMAINS required (comma-separated, e.g. 'acme.com,www.acme.com')}"

# Optional: short label for the bearer token row so admins can tell
# tokens apart if they provision multiple per org later.
TOKEN_NAME="${TOKEN_NAME:-default}"

# Public site id has a strict format (matches ingest validator regex
# ^wb_(live|test)_[A-Za-z0-9]{16,}$). We derive it from org+slug so
# re-runs land on the same site.
PUBLIC_SITE_ID="${PUBLIC_SITE_ID:-wb_live_$(printf "%s_%s" "$ORG_SLUG" "$SITE_NAME" | \
  openssl dgst -sha256 -binary | xxd -p -c 200 | head -c 20)}"

PSQL() {
  docker compose exec -T -e PGPASSWORD=postgres postgres \
    psql -U postgres -d webalytics -qtAX -v ON_ERROR_STOP=1 "$@"
}

# 1. Org (idempotent by slug)
ORG_ID=$(PSQL -c "
  INSERT INTO organizations (slug, name)
  VALUES ('$ORG_SLUG', '$ORG_NAME')
  ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
  RETURNING id;
")

# 2. Site (idempotent by public_site_id)
SITE_ID=$(PSQL -c "
  INSERT INTO sites (organization_id, public_site_id, name)
  VALUES ('$ORG_ID', '$PUBLIC_SITE_ID', '$SITE_NAME')
  ON CONFLICT (public_site_id) DO UPDATE SET name = EXCLUDED.name
  RETURNING id;
")

# 3. Domains. First domain becomes primary; rest are aliases.
IFS=',' read -ra DOMAIN_LIST <<< "$DOMAINS"
PRIMARY=1
for d in "${DOMAIN_LIST[@]}"; do
  # Trim whitespace (allows DOMAINS="a.com, b.com")
  d=$(echo "$d" | xargs)
  if [ "$PRIMARY" = "1" ]; then
    PSQL -c "
      INSERT INTO domains (site_id, hostname, is_primary)
      VALUES ('$SITE_ID', '$d', TRUE)
      ON CONFLICT (site_id, hostname) DO UPDATE SET is_primary = TRUE;
    "
    PRIMARY=0
  else
    PSQL -c "
      INSERT INTO domains (site_id, hostname)
      VALUES ('$SITE_ID', '$d')
      ON CONFLICT (site_id, hostname) DO NOTHING;
    "
  fi
done

# 4. Token (always rotate on re-run so the printed value is the truth)
RAW_TOKEN="wb_pat_live_$(openssl rand -hex 16)"
TOKEN_HASH=$(printf "%s" "$RAW_TOKEN" | openssl dgst -sha256 -binary | xxd -p -c 200)
TOKEN_PREFIX=${RAW_TOKEN:0:20}

PSQL -c "
  DELETE FROM api_tokens WHERE organization_id = '$ORG_ID' AND name = '$TOKEN_NAME';
  INSERT INTO api_tokens (organization_id, name, token_hash, token_prefix, scopes)
  VALUES ('$ORG_ID', '$TOKEN_NAME', decode('$TOKEN_HASH', 'hex'), '$TOKEN_PREFIX',
          ARRAY['read:events','write:sites']::TEXT[]);
"

cat <<EOF

PROVISIONED OK
  organization:      $ORG_NAME ($ORG_SLUG)
  organization_id:   $ORG_ID
  site:              $SITE_NAME
  site_uuid:         $SITE_ID
  public_site_id:    $PUBLIC_SITE_ID
  domains:           $DOMAINS
  api_token:         $RAW_TOKEN

Tracker install (client-side; public_site_id is safe to embed):
  import { init } from "@webalytics/tracker";
  init({
    host:   "\${WEBALYTICS_HOST:-https://<your-deploy>}",
    siteId: "$PUBLIC_SITE_ID",
  });

Dashboard install (server-side only; token stays on the server):
  WEBALYTICS_API_HOST=https://<your-deploy>
  WEBALYTICS_API_TOKEN=$RAW_TOKEN
  WEBALYTICS_SITE_UUID=$SITE_ID

EOF

# Also write a machine-readable env file next to seed.sh so automation /
# dashboards can source it directly. Path is keyed by org slug.
mkdir -p deploy/tenants
OUT="deploy/tenants/${ORG_SLUG}.env"
umask 077
cat > "$OUT" <<EOF
# Auto-generated by provision-site.sh. Contains a secret; keep private.
WEBALYTICS_ORG_SLUG=$ORG_SLUG
WEBALYTICS_ORG_ID=$ORG_ID
WEBALYTICS_SITE_UUID=$SITE_ID
WEBALYTICS_PUBLIC_SITE_ID=$PUBLIC_SITE_ID
WEBALYTICS_TOKEN=$RAW_TOKEN
EOF
chmod 600 "$OUT"
echo "Credentials also written to $OUT"
